apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: theoremlib-db
spec:
  serviceName: theoremlib-db
  replicas: 1
  selector:
    matchLabels:
      app: theoremlib-db
  template:
    metadata:
      labels:
        app: theoremlib-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: theoremlib-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: theoremlib-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: theoremlib
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-db
        configMap:
          name: theoremlib-initdb
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi