apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: theoremlib-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: theoremlib-initdb
data:
  init-db.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE SCHEMA IF NOT EXISTS theoremlib;
    ALTER DATABASE theoremlib SET search_path TO theoremlib, public;
    
    CREATE INDEX IF NOT EXISTS theorem_embedding_idx ON theorems 
    USING ivfflat (theorem_embedding vector_l2_ops)
    WITH (lists = 100);
    
    CREATE INDEX IF NOT EXISTS proof_embedding_idx ON theorems 
    USING ivfflat (proof_embedding vector_l2_ops)
    WITH (lists = 100);
    
    CREATE INDEX IF NOT EXISTS theorem_text_idx ON theorems 
    USING gin(to_tsvector('english', theorem_text));
    
    CREATE INDEX IF NOT EXISTS proof_text_idx ON theorems 
    USING gin(to_tsvector('english', proof_text));